### ISSUE TITLE
Edit: Hosting front-end with AWS EB. No longer Azure.

### ISSUE THREAD

**Issue by hornunjb** [hornunjb/AnxietyKnot#15]
Setup hosting for back-end Node.js server application using Microsoft Azure

**Comment by uc-kokengna** [comment]
successfully deployed files to AWS S3 static hosting web server. Everything ran relatively smoothly. Need to make a few adjustments to the environment.ts and environment.prod.ts files to correct an apiUrl issue that showed up in the static hosting environment webpage html. I did not have time to test if the deployment successfully sent journal post data to the backend server, but will look into this.

**Comment by uc-kokengna** [comment]
Found issue, had to manually run "npm run start:server" on local laptop. Believe this is due to having my local IP connected to the backend servers, which causes a manually run. Will attempt to fix. If it takes too long I will temporarily skip and work on more important matters.

**Comment by uc-kokengna** [comment]
Seems the only way -at the moment- to correct this issue is to upgrade my free use accounts or use some form of networking trickery. I'm no longer going to consider this a huge priority as it's causing me too much time to figure it out. Will close this matter, but will see if I can run accross an answer.

**Comment by uc-kokengna** [comment]
Seems the only way -at the moment- to correct this issue is to upgrade my free use accounts or use some form of networking trickery. I'm no longer going to consider this a huge priority as it's causing me too much time to figure it out. Will close this matter, but will see if I can run accross an answer.
