### ISSUE TITLE
Linking feelings after journaling to a specific user

### ISSUE THREAD

**Issue by hornunjb** [hornunjb/AnxietyKnot#38]
When a user adds a mood rating after they save an entry - link their saved mood and journal entry date to their user ID

**Comment by hornunjb** [comment]
As of merging https://github.com/hornunjb/AnxietyKnot/pull/79 - portion is complete for FREEFORM JOURNALING

**Comment by uc-kokengna** [comment]
![image](https://user-images.githubusercontent.com/70075871/160439358-581d13cd-4e62-4ada-bd12-987aad04939c.png)

Examined this on Main branch. Previous Posts appear more than once on Journal Display after submitting and redirected to JournalDisplay Page. Problems primarily caused by code re-routing user after submit. Fix is to manually refresh page or modify re-route and refresh page codes.
![image](https://user-images.githubusercontent.com/70075871/160440066-c2b800c6-c6c9-4102-90fb-6aa361aedb1b.png)
